name: Build and Deploy Code

on: [push, pull_request] # push # [push, pull_request] # [push]
  # push:
  #   branches: ["main"] #["main", "another_branch"]
  #     - "main"
  #     - "another_branch"
  # pull_request:
  #   branches:
  #     - "test_branch"
jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to imfilip
        run: echo "hello imfilip!"
      # - name: installing python
      #   run: sudo apt install python3
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: installing all dependencies
        run: pip install -r requirements.txt
      - name: tests with pytest
        run: | 
          pip install pytest
          pytest